# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(max_length=32, verbose_name='id')),
                ('news_title', models.CharField(max_length=100, verbose_name='\u65b0\u95fb\u6807\u9898')),
                ('image_url', models.CharField(max_length=255, verbose_name='\u56fe\u7247\u94fe\u63a5')),
                ('share_url', models.CharField(max_length=255, verbose_name='\u65b0\u95fb\u94fe\u63a5')),
            ],
        ),
    ]
